Django/1012/1012/accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.main, name="main"),
    path('signup/', views.signup, name="signup"),
    path('index/', views.index, name="index"),
    path('<int:user_pk>/', views.detail, name="detail"),
]

Django/1012/1012/articles/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('', views.index, name="index")
    
]

Django/1012/1012/pjt1011/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('articles.urls')),
    path('', include('accounts.urls')),
]

Django/1012/1012/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

Django/1012/1012/articles/models.py
from django.db import models

# # Create your models here.

class Article(models.Model):
    movie_name = models.CharField(max_length=25)
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/1012/1012/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

# AUTH_USER_MODEL의 default 값은 'auth.User' 기본적으로 장고가 제공하는 user값
# settings.py에서 디폴트 값을 바꾸고 AUTH_USER_MODEL = 'accounts.User' 어카운트 앱안의 내가 정의한 User class을 사용해줘라
# 이것의 사용은 get_user_model()로 하는 것
# 말하자면 내가 지금 model에 User을 상속받아와서 정의했는데 이 모델은 언제든지 내가 custom 할 수 있음
# 변동 가능성이 있는 친구들은 import를 User로 하는것이 아닌 변수화 해서 받아오는것이 항상 좋음 그래서 get_user_model을 사용하는것


# usercreationform 에서는 사용자이름, 비밀번호1, 비밀번호2(비밀번호 1 대조 위한 값)
# 즉, 다시 말해서 상속 받아온 값 이외에도 email값을 추가해주어야한다.
class UserForm(UserCreationForm):
    # email = forms.EmailField(label="email")
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']

Django/1012/1012/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = 'Article'
        fields = ['title', 'content', 'movie_name']

        labels = {
            'title' : '리뷰 제목',
            'content' : '리뷰 내용',
            'movie_name' : '영화제목',            
        }

Django/1012/1012/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from .forms import UserForm
# Create your views here.

def main(request):
    return render(request, 'accounts/main.html')

def index(request):
    user_list = get_user_model().objects.order_by('-id')

    context = {
        'user_list' : user_list,
    }

    return render(request, 'accounts/index.html', context)

def signup(request):
    if request.method == "POST":
        signup_list = UserForm(request.POST)
        if signup_list.is_valid():
            signup_list.save()
            return redirect('account:index')

    else:
        signup_list = UserForm()
    
    context = {
        'signup_list' : signup_list,
    }

    return render(request, 'accounts/signup.html', context)

def detail(request, user_pk):
    user_detail = get_user_model().objects.get(pk=user_pk)

    context = {
        'user_detail' : user_detail,
    }

    return render(request, 'accounts/detail.html', context)

Django/1012/1012/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# # Create your views here.

def index(request):
    return render(request, 'articles/index.html')

Django/1012/1012/articles/templates/articles/index.html
{% comment %} {% extends 'base.html' %}

{% block content %}{% endblock content %} {% endcomment %}

Django/1012/1012/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>movie</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- style.css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <!-- animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  </head>

  <body>
    {% block nav %}
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid flex-column">
          <a class="me-0 navbar-brand" href="/">
            <img src="{% static 'image/logo.png' %}" class="img-size">
          </a>
          <div class="d-flex my-3 fw-light text-space">
            <a class="btn btn-outline-light nav-link border px-3 mx-3" aria-current="page" href="/">Home</a>
            <a class="btn btn-outline-light nav-link border px-3 mx-3" href="/accounts/index">Users</a>
            <a class="btn btn-outline-light nav-link border px-3 mx-3" href="{% url 'account:signup' %}">Sign Up</a>
          </div>
        </div>
      </div>
    </nav>
  {% endblock nav %}
  {% block content %}{% endblock content %}
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>