Django/0929/Todo/urls.py
from django.urls import path
from . import views

app_name = 'Todo'

urlpatterns = [
    path('', views.main, name='main'),
    path('todo/', views.todo, name='todo'),
    path('create/', views.create, name='create'),
    path('delete/<int:todo_pk>/', views.delete, name='delete'),
    path('update/<int:todo_pk>/', views.update, name='update'),
    path('check/<int:todo_pk>/', views.check, name='check'),
]

Django/0929/TodoList/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Todo.urls')),
]

Django/0929/Todo/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    content = models.CharField(max_length=80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

Django/0929/Todo/views.py
from django.shortcuts import render, redirect
from .models import Todo


# Create your views here.

#main page
def main(request):
    return render(request, 'Todo/main.html')

#todo page
def todo(request):
    result = []
    # create 한 쿼리문을 사이트에 받아온다
    Todo_result = Todo.objects.order_by('id').all()
    result.append(Todo_result)

    context = {
        'result' : result,
    }

    return render(request, 'Todo/todo.html', context)

def create(request):
    # 제출 받은 값을 create 해준다
    today = request.GET.get('today')
    priority = request.GET.get('priority')
    date = request.GET.get('date')
    print(today, priority, date)

    Todo.objects.create(content=today, priority=priority, deadline=date)

    return redirect('Todo:todo')

# update
def update(request, todo_pk):
    id = Todo.objects.get(id = todo_pk)
    if id.completed == False:
        id.completed = True
    else:
        id.completed = False
    id.save()

    return redirect('Todo:todo')



# delete
def delete(request, todo_pk):
    id = Todo.objects.get(id = todo_pk)
    id.delete()

    return redirect('Todo:todo')


# checkbox check 했을때 새로고침해도 reset 방지 = redirect

def check(request, todo_pk):
    id = Todo.objects.get(id = todo_pk)
    if id.completed == False:
        id.completed == True
    else:
        id.completed == False
    id.save()
        

    return redirect('Todo:todo')

Django/0929/Todo/templates/Todo/main.html
{% extends 'base.html' %}
{% block content %}
  <div class="size d-flex flex-column justify-content-center align-items-center">
    <h1 class="text-center fw-light">To-Do List</h1>
    <a href="todo/"><button class="btn btn-outline-warning text-center mt-3">Start !</button></a>
  </div>
{% endblock %}

Django/0929/Todo/templates/Todo/todo.html
{% extends 'base.html' %}
{% block content %}
<div class="size bg-light d-flex flex-column justify-content-center">
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class="row-col-1 m-3">
      <div class="col">
        <h1 class="text-center fw-lighter">To-Do List</h1>
        <hr>
      </div>
      <div class="col">
        <form action="{% url 'Todo:create' %}">
          <div class="input-group mb-3">
            <button class="btn btn-outline-success" type="button" for="today">오늘 할 일</button>
            <input type="text" class="form-control bg-light" name="today" autocomplete="off" required>
          </div>
          <div class="input-group mb-3">
            <button class="btn btn-outline-success" type="button">우선 순위</button>
            <select class="form-select bg-light" name="priority" required>
              <option selected></option>
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
            </select>
          </div>
          <div class="input-group mb-3">
            <button class="btn btn-success">마감 기한</button>
            <input type="date" class="form-control bg-light" name="date" autocomplete="off" required>
          </button>
          <span class="ms-3">
            <button type="submit" class="btn btn-dark" name="addTodo"><i class="bi bi-plus-circle"></i> Add</button> 
          </span>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- view point 휴대폰 화면 크기 정도? -->
  <div class="m-4 d-block d-md-none">
    <!-- 그냥 체크박스로 해서 시작 시기, 마감 기한, 체크 항목 정도로 바꾸기 -->
    <!-- form check 말고 따로 checkbox를... -->
    <!-- interminate = False 기본 값으로 설정 되어있다. value를 통해서 조작 가능.. -->
    <h3 class="my-3 text-center">체크 리스트</h3>
    {% for elements in result %}
      {% for element in elements %}
        <form action="{% url 'Todo:update' element.id %}">
          <div class="fw-bold">
            {% if element.completed == 1 %}
            <button class="btn btn-light border-light px-1 py-0" id="checkinput" style="border-radius: .3rem;" value=""><i class="bi bi-check-lg text-center text-primary fw-bolder"></i></button>
            <label class="fs-6 align-middle mx-2" for="checkinput">{{ element.content }}</label>
            {% else %}
            <button class="btn btn-light px-1 py-0" id="checkinput" style="border-radius: .3rem; width: 25.99px; height: 25.99px;"> <a href="{% url 'Todo:update' element.id %}"></a></button>
            <label class="fs-6 align-middle mx-2" for="checkinput">{{ element.content }}</label>
            {% endif %}
          </div>
          <hr>
        </form>
      {% endfor %}
    {% endfor %}
  </div>
  <!-- view point 아이패드 부터 컴퓨터 크기 정도? -->
  <div class="col-12 p-5 d-none d-md-block">
    <table class="table text-center">
      <thead class="fw-lighter" style="background-color: rgb(139, 190, 139);">
        <tr>
          <th scope="col" class="letter-space" style="width: 10rem;">우선 순위</th>
          <th scope="col" class="letter-space">할 일 내용</th>
          <th scope="col" class="letter-space" style="width: 14rem;">생성 날짜</th>
          <th scope="col" class="letter-space" style="width: 14rem;">마감 기한</th>
          <th scope="col" class="letter-space" style="width: 10rem;">진행 상태</th>
          <th scope="col" class="letter-space" style="width: 14rem;">상태 변경</th>
          <th scope="col" class="letter-space" style="width: 5rem;">삭제</th>
        </tr>
      </thead>
      <tbody class="align-middle">
        {% for elements in result %}
          {% for element in elements %}
          <tr class="text-center">
            {% if element.completed == 1 %}
            <td class="text-success fw-semibold">{{ element.priority }}</td>
            <td class="text-success fw-semibold" style="width: 25rem;">{{ element.content }}</td>
            <td class="text-success fw-semibold">{{ element.created_at| date:"Y-m-d" }}</td>
            <td class="text-success fw-semibold">{{ element.deadline| date:"Y-m-d" }}</td>
            <td><a href="{% url 'Todo:update' element.id %}">&#x1F646;</a></td>
            <td style="width: 6rem;">&#x2705; 완료 !</td>
            {% else %}
            <td>{{ element.priority }}</td>
            <td style="width: 25rem;">{{ element.content }}</td>
            <td>{{ element.created_at| date:"Y-m-d" }}</td>
            <td>{{ element.deadline| date:"Y-m-d" }}</td>
            <td><a href="{% url 'Todo:update' element.id %}">&#x1F645;</a></td>
            <td style="width: 6rem;">&#x274E; 언제 해 ?</td>
            {% endif %}
            <td><a href="{% url 'Todo:delete' element.id %}" class="text-dark"><i class="bi bi-x-lg" style="line-height: 1.5;"></i></a></td>
          </tr>
          {% endfor %}
        {% endfor %}
      </tbody>
    </table>
  </div>  
</div>
{% endblock %}

Django/0929/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TodoList</title>
  <!-- CSS only -->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
 <!-- bootstrap-icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <style>
    .size {
      width: 100vw;
      height: 100vh;
    }
    
    .letter-space {
      letter-spacing : -1px;
    }
  </style>
</head>
<body>
  {% block content %}
  {% endblock %}
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>