Django/1018/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/', views.detail, name='detail'),
]

Django/1018/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('<int:pk>/edit/', views.update, name="update"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/comments/', views.comments_create, name="comments_create"),
    path('<int:article_pk>/comments/<int:comment_pk>/edit/', views.comments_edit, name="comments_edit"),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name="comments_delete"),
]

Django/1018/pjt1017/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('article/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/1018/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

Django/1018/articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from django.conf import settings
# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True, upload_to='images/')
    thumbnail = ProcessedImageField(
        upload_to='images/', 
        blank=True,
        processors=[ResizeToFill(1500, 1000)], 
        format='JPEG',
        options={'quality': 80})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)


class Comment(models.Model):
    content = models.CharField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)

Django/1018/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'last_name', 'first_name', 'email', 'password1', 'password2']

        

Django/1018/articles/forms.py
from django import forms
from .models import Article, Comment
from django.forms import TextInput

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'image', 'thumbnail']

        labels = {
            'title' : '제목',
            'content' : '내용',
            'image' : '이미지',
            'thumbnail' : '썸네일',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]
        labels = {
            "content" : "",
        }
        widgets = {
            'content' : TextInput(attrs={
                'class' : 'border-0 border-bottom border-1 border-dark rounded-0 mx-1',
                'style' : 'background: transparent;',
                'placeholder' : '댓글을 입력해주세요',
            }),
        }
        

        

Django/1018/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, login as auth_login, logout as auth_logout
from .forms import UserCreateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from articles.models import Article, Comment
# Create your views here.

def login(request):
    if request.method == "POST":
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('accounts:login')
    else:
        login_form = AuthenticationForm()
    
    context = {
        'login_form' : login_form,
    }
    
    return render(request, 'accounts/main.html', context)

def signup(request):
    if request.method == "POST":
        signup_form = UserCreateForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            return redirect('accounts:login')

    else:
        signup_form = UserCreateForm()

    context = {
        'signup_form' : signup_form,
    }

    return render(request, 'accounts/signup.html', context)

@login_required
def logout(request):
    auth_logout(request)
    messages.warning(request, 'Bye!')
    return redirect('accounts:login')


@login_required
def detail(request, user_pk):
    article_list = Article.objects.filter(user_id=user_pk)
    comment_list = Comment.objects.filter(user_id=user_pk)

    context = {
        'article_list' : article_list,
        'comment_list' : comment_list,
    }

    return render(request, 'accounts/profile.html', context)

Django/1018/articles/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.

@login_required
def index(request):
    card_list = Article.objects.order_by('-id')
    
    context = {
        'card_list' : card_list,
    }

    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == "POST":
        create_form = ArticleForm(request.POST, request.FILES)
        if create_form.is_valid():
            article = create_form.save(commit=False)
            article.user = request.user
            article.save()
            messages.success(request, '글 작성 완료!')
            return redirect('articles:index')
    else:
        create_form = ArticleForm()
    
    context = {
        'create_form' : create_form,
    }
        
    return render(request, 'articles/create.html', context)

@login_required
def detail(request, pk):
    article_detail = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = article_detail.comment_set.all()
    context = {
        'article_detail' : article_detail,
        'comment_form' : comment_form,
        'comments' : comments,
    }

    return render(request, 'articles/detail.html', context)

@login_required
def delete(request, pk):
    Article.objects.get(pk=pk).delete()
    
    return redirect('articles:index')

@login_required
def update(request, pk):
    article_update = Article.objects.get(pk=pk)
    if request.method == "POST":
        update_form = ArticleForm(request.POST, request.FILES, instance=article_update)
        if update_form.is_valid():
            update_form.save()
            messages.success(request, '수정 완료!')
            return redirect('articles:index')
    else:
        update_form = ArticleForm(instance=article_update)

    context = {
        'update_form' : update_form,
    }

    return render(request, 'articles/edit.html', context)

@login_required
def comments_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.article = article
        comment.save()

    return redirect('articles:detail', article.pk)


@login_required
def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if comment.user == request.user:
        comment.delete()
    return redirect('articles:detail', article_pk)

@login_required
def comments_edit(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    
    if request.method == "POST":
        comment_edit = CommentForm(request.POST, instance=comment)
        if comment.user == request.user:
            if comment_edit.is_valid():
                comment_edit.save()
                return redirect('articles:detail', article_pk)
    else:
        comment_edit = CommentForm(instance=comment)
 
    context = {
        'comment_edit' : comment_edit,
    }

    return render(request, 'articles/detail.html', context)

Django/1018/accounts/templates/accounts/main.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block nav %}{% endblock nav%}
{% block content %}
  <div class="background-size">
    <nav class="navbar navbar-expand-lg bg-none">
      <div class="container-fluid justify-content-between bg-none">
        <a class="navbar-brand" href="{% url 'articles:index' %}"><img src="{% static 'image/logo.png' %}" style="width: 140px; height: 30px;"></a>
        {% if request.user.is_authenticated %}
          <div class=" align-middle">
            <span class="fw-lighter">
              <a href="{% url 'accounts:detail' user.pk %}" class="text-decoration-none text-dark">{{ user }}님</a>
            </span>
            <a href="{% url 'accounts:logout' %}" class="text-dark fw-bolder me-4 text-decoration-none">&#128075 B y e !</a>
          </div>
        {% endif %}
      </div>
    </nav>
    {% if request.user.is_authenticated %}
      <div class="background-view container d-flex flex-column align-items-center">
        <form action="{% url 'articles:index' %}" class="mt-3">
          <h1 class="text-size fw-lighter" style="letter-spacing: -2px;">Hello,
            {{ request.user }}</h1>
          <div class="text-center">
            <button class="btn btn-outline-light border border-0 rounded-1 fw-bolder text-dark rounded-5 px-3 py-2">
              h o m e
            </button>
          </div>
        </form>
        <form action="{% url 'accounts:detail' user.pk %}">
          <div class="text-center">
            <button class="btn btn-outline-light border border-0 rounded-1 fw-bolder text-dark rounded-5 px-3 py-2">
              m y p r o f i l e
            </button>
          </div>
        </form>
      </div>
    {% else %}
      <div class=" background-view my-3 d-flex justify-content-center align-items-center p-3">
        <div class="container container-color rounded-4 shadow-lg pullUp">
          <div class="row row-cols-1 row-cols-md-2">
            <div class="col d-flex justify-content-center">
              <img src="{% static 'image/loading_portrait.gif' %}" class="img-hover">
            </div>
            <div class="col d-flex flex-column justify-content-center align-items-center mb-4">
              <form action="" method="POST" class="text-white fw-bolder align-middle" style="width: 20rem;">
                {% csrf_token %}
                {% bootstrap_form login_form %}
                <div class="text-end">
                  <button type="submit" class="btn p-0">
                    <a class="text-white fw-bolder">로그인</a>
                  </button>
                </div>
                <div class="text-white text-center fw-bolder opacity-75 mt-4 p-1" style="background-color: #262f3672">
                  아직 가입하지 않았다면?
                  <a href="{% url 'accounts:signup' %}" class="text-warning">회원가입</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endif %}

  </div>
{% endblock content %}

Django/1018/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="mt-5 container row-cols-1 d-flex">
    <div class="card card-bg-color p-3">
      <div class="card-body">
        <div class="text-size fw-bolder px-3 text-center" style="letter-spacing: -2px;">
          <i>{{ request.user }}</i>
        </div>
        <br>
        <div class="d-flex justify-content-between">
          <a class="border-0 text-decoration-none text-dark d-flex" type="button" data-bs-toggle="collapse" data-bs-target="#collapseArticleList" aria-expanded="false">
            <div class="vr px-1"></div>
            <h5 class="fw-bolder m-0 ms-2">내가 쓴 글</h5>
          </a>
          <div class="text-end badge bg-primary">
            <span class="align-middle">{{ article_list.count }}</span>
          </div>
        </div>
        <hr>
        <div class="collapse" id="collapseArticleList">
          {% for article in article_list %}
            <div class="container bg-light rounded-2 border border-dark border-1 shadow-lg py-2 px-3">
              <h5 class="m-0 py-1">
                <a href="{% url 'articles:detail' article.pk %}" class="text-decoration-none">
                  {{ article.title }}
                </a>
              </h5>
              <hr class="my-2">
              <p class="date-size m-0 fw-light text-secondary">{{ article.created_at }}
                |
                {{ article.updated_at }}
              </p>
            </div>
            <hr>
          {% endfor %}
        </div>
        <!-- 댓글 -->
        <div class="d-flex justify-content-between">
          <a class="border-0 text-decoration-none text-dark d-flex" type="button" data-bs-toggle="collapse" data-bs-target="#collapseCommentList" aria-expanded="false">
            <div class="vr px-1"></div>
            <h5 class="fw-bolder m-0 ms-2">내가 쓴 댓글</h5>
          </a>
          <div class="text-end badge bg-primary">
            <span class="align-middle">{{ comment_list.count }}</span>
          </div>
        </div>
        <hr>
        <div class="collapse" id="collapseCommentList">
          {% for comment in comment_list %}
            <div class="container rounded-2 border border-dark border-1 shadow-lg py-2 px-3">

              <h5 class="mt-2 mb-0">
                <a href="{% url 'articles:detail' comment.article_id %}" class="text-decoration-none text-dark">{{ comment.content }}</a>
              </h5>

              <hr class="my-2">
              <p class="date-size m-0 fw-light text-light">{{ comment.created_at }}
              </p>
            </div>
            <hr>
          {% endfor %}
        </div>
      </div>
    </div>

  {% endblock content %}

Django/1018/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="d-flex justify-content-center align-items-center my-5">
    <div class="container">
      <form action="" method="POST" class="border border-2 border-dark shadow-lg rounded-2 mx-2 p-5 form-style">
        {% csrf_token %}
        {% bootstrap_form signup_form %}
        <div class="text-end">
          <input type="submit" class="btn btn-dark" value="회원가입">
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

Django/1018/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container py-4">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form create_form %}
      <div class="text-end">
        <input type="submit" class="btn btn-dark" value="작성하기">
      </div>
    </form>
  </div>

{% endblock content %}

Django/1018/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="background-view px-3 py-5">
    <div class="px-3 container card form-style border border-3 p-0 shadow-lg">
      <h1 class="text-white text-center mt-3 text-size">
        <i>{{ article_detail.title }}</i>
      </h1>
      <div class="d-flex justify-content-center">
        <div class="text-center badge bg-light text-black py-2 px-4 fw-semibold border border-2 border-dark lh-1">
          <i>{{ article_detail.user }}</i>
        </div>
      </div>
      <div class="text-end">
        <p class="fw-lighter m-0">글 생성일 :
          {{ article_detail.created_at }}
        </p>
        <p class="fw-lighter">마지막 수정일 :
          {{ article_detail.updated_at }}</p>
      </div>
      <div class="text-end">
        <a href="{% url 'articles:update' article_detail.pk %}" class="text-decoration-none btn btn-warning fw-light opacity-75">
          글 수정
        </a>
      </div>
      <div class="d-flex justify-content-center">
        <img src="{% static 'image/rabbit.png' %}" class="comment-icon-size">
        <form action="{% url 'articles:comments_create' article_detail.pk %}" method="POST" class="d-flex w-50">
          {% csrf_token %}
          {% bootstrap_form comment_form layout='inline'%}
          <input type="submit" class="btn btn-none p-0 rounded-5 border-0 ms-2" value="&#10004;">
        </form>
      </div>
      <a class="mt-4 text-decoration-none text-dark" data-bs-toggle="collapse" href="#collapseComment" role="button" aria-expanded="false">
        <div class="text-center">
          <h5 class="fw-bolder btn btn-outline-light mb-0 border-0 position-relative">
            <i>Comments</i>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
              {{ comments.count }}</span>
          </h5>
          <p class="comment-text-size mb-0">댓글을 모두 확인하려면 C L I C K !</p>
        </div>
      </a>
      <div class="collapse" id="collapseComment">
        {% for comment in comments %}
          {% if request.method == "GET" %}
            <hr>
            <div class="container bg-light rounded-2 shadow-lg px-3 py-2 border border-dark border-2">
              <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                  <img src="{% static 'image/rabbit.png' %}" class="comment-icon-size">
                  <p class="mx-2 mb-0">{{ comment.user }}</p>
                </div>
                <div>
                  <div class="d-flex align-items-center">
                    <!-- 댓글 수정 -->
                    <form action="" method="POST" class="text-decoration-none">
                      {% if comment.user == request.user %}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-none border-0 align-middle">
                          <i class="bi bi-pencil-square fs-3"></i>
                        </button>
                      {% endif %}
                    </form>
                    <!-- 댓글 삭제 -->
                    <form action="{% url 'articles:comments_delete' article_detail.pk comment.pk %}" method="POST" class="ms-3 text-decoration-none text-danger">
                      {% csrf_token %}
                      {% if comment.user == request.user %}
                        <button class="btn btn-none p-0 border-0 align-middle" type="submit"><img src="{% static 'image/trash.png' %}" class="comment-icon-size"></button>
                      {% endif %}
                    </form>
                  </div>
                </div>
              </div>
              <hr class="my-2 mb-0">
              <p class="pt-2 mb-0 align-middle">{{ comment.content }}</p>
              <p class="text-end mb-0 comment-text-size">{{ comment.created_at }}</p>
            </div>
          {% else %}
            <hr>
            <div class="container bg-light rounded-2 shadow-lg px-3 py-2 border border-dark border-2">
              <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                  <img src="{% static 'image/rabbit.png' %}" class="comment-icon-size">
                  <p class="mx-2 mb-0">{{ comment.user }}</p>
                </div>
              </div>
              <hr>
              {% if request.user.pk == comment.user.pk %}
                <form action="{% url 'articles:comments_edit' article_detail.pk comment.pk %}" method="POST" class="">
                  {% csrf_token %}
                  {% bootstrap_form comment_form %}
                  <div class="text-end">
                    <button type="submit" class="btn btn-dark">제출</button>
                  </div>
                </form>

              {% else %}
                <p class="pt-2 my-2 mb-0 align-middle">{{ comment.content }}</p>
                <p class="text-end mb-0 comment-text-size">{{ comment.created_at }}</p>
              {% endif %}
            </div>
          {% endif %}
        {% endfor %}
      </div>
      <div class="card-img-top text-center p-3">
        {% if article_detail.image %}
          <img src="{{ article_detail.image.url }}" class="w-75 border border-3 border-dark rounded-3">
        {% else %}
          <img src={% static 'image/1500x1000.png' %} class="w-75 border border-3 border-dark rounded-3">
        {% endif %}
      </div>
      <hr>
      <pre class="text-center">{{ article_detail.content }}</pre>
    </div>
  </div>
{% endblock content %}

Django/1018/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container py-4">
    <form action="" method="POST" enctype="multipart/form-data" class="text-white mb-0">
      {% csrf_token %}
      {% bootstrap_form update_form %}
      <div class="text-end">
        <input type="submit" class="btn btn-dark" value="수정">
      </div>
    </form>
  </div>
{% endblock content %}

Django/1018/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="background-view">
    <div class="container-fluid text-center">
      <a href="{% url 'articles:create' %}">
        <img src="{% static 'image/rabbit.png' %}" class="img-size">
      </a>
    </div>
    <div class="container">
      <div class="row row-cols-1 row-cols-md-3">
        {% for newjeans in card_list %}
          <div class="container my-3">
            <div class="col card rounded-5 my-3 px-0 h-100 card-style shadow-lg">
              {% if newjeans.thumbnail %}
                <img src="{{ newjeans.thumbnail.url }}" class="card-img-top rounded-5 shadow opacity-75" alt="">
              {% else %}
                <img src="{% static 'image/1500x1000.png' %}" class="card-img-top rounded-5" alt="">
              {% endif %}
              <div class="card-body rounded-5 text-center align-middle">
                <a href="{% url 'articles:detail' newjeans.pk %}" class="text-white text-decoration-none opacity-75 pt-0 pb-1">
                  <h3 class="fw-border m-0">
                    <i class="text-center align-middle">&#10024;{{ newjeans.title }}</i>
                  </h3>
                </a>
                <a href="{% url 'articles:delete' newjeans.pk %}" class="text-end position-absolute top-0 end-0 opacity-50"><img src="{% static 'image/trash.png' %}" class="icon-size"></a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endblock content %}

Django/1018/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- style.css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
    <!-- animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/animations.css' %}" type="text/css">
  </head>

  <body style="background-color: #95A7B7">

    {% block nav %}
      <nav class="navbar navbar-expand-lg bg-none">
        <div class="container-fluid justify-content-between bg-none">
          <div class="align-middle">
            <a class="navbar-brand" href="{% url 'accounts:login' %}"><img src="{% static 'image/logo.png' %}" style="width: 140px; height: 30px;"></a>
            <a href="{% url 'articles:index' %}" class="text-decoration-none">
              <i class="bi bi-house-fill fs-3 align-middle text-white"></i>
            </a>
          </div>
          {% if request.user.is_authenticated %}
            <div class="align-middle">
              <span class="text-white fw-lighter">
                <a href="{% url 'accounts:detail' user.pk %}" class="text-decoration-none text-light">{{ user }}님</a>
              </span>
              <a href="{% url 'accounts:logout' %}" class="text-white fw-bolder text-decoration-none me-4">&#128075 B y e !</a>
            </div>
          {% endif %}
        </div>
      </div>
    </nav>

  {% endblock nav %}

  {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="text-center bg-none opacity-75 py-3 my-3 fs-5" {% endif %}>{{ message }}</div>
    {% endfor %}
  {% endif %}
  {% block content %}{% endblock content %}

  <!-- javascript -->
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>

</html>